//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartographie.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Identifiant { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public string Complement_Adresse { get; set; }
        public string Code_Postal { get; set; }
        public string Ville { get; set; }
        public string Pays { get; set; }
        public string Dimension_Entreprise { get; set; }
        public string Url_Site { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public int Identifiant_Categorie { get; set; }
    
        public virtual Categorie Categorie { get; set; }
    }
}
